---
title: Modern Resume
timezone: IST
markdown: kramdown
safe: true
local: true  #Enable for github

# edit here to achieve your personal greatness
url: https://sumit.murari.me
baseurl: ""

sass:
  sass_dir: _scss
  style: :compressed